{{- if not (lookup "v1" "PersistentVolume" "" "mongo-pv") }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  namespace: wanderlust
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/db
{{- end }}
